import { Company } from './company'
import { Post } from './post'
import { ObjectType, Field, ID, Int, registerEnumType } from '@nestjs/graphql'
import { GraphQLJSONObject } from 'graphql-type-json'

@ObjectType({
	description:
		'generated by [prisma-class-generator](https://github.com/kimjbstar/prisma-class-generator)',
})
export class Author {
	@Field((type) => ID)
	id: number = undefined

	@Field((type) => Company)
	company: Company = undefined

	@Field((type) => String)
	name: string = undefined

	@Field((type) => GraphQLJSONObject, { nullable: true })
	extra?: object = undefined

	@Field((type) => Date)
	createdAt: Date = undefined

	@Field((type) => Date)
	updatedAt: Date = undefined

	@Field((type) => Date, { nullable: true })
	deletedAt?: Date = undefined

	@Field((type) => [Post])
	posts: Post[] = undefined

	@Field((type) => Int)
	companyId: number = undefined
}
