import { Glass } from './glass'
import { Technique } from './technique'
import { Garnish } from './garnish'
import { Recipe } from './recipe'
import { Ingredient } from './ingredient'
import { ObjectType, Field, ID, Int, registerEnumType } from '@nestjs/graphql'
import { GraphQLJSONObject } from 'graphql-type-json'

@ObjectType({
	description:
		'generated by [prisma-class-generator](https://github.com/kimjbstar/prisma-class-generator)',
})
export class Cocktail {
	@Field((type) => ID)
	id: number = undefined

	@Field((type) => String)
	name: string = undefined

	@Field((type) => String)
	nameEnglish: string = undefined

	@Field((type) => String, { nullable: true })
	desc?: string = undefined

	@Field((type) => String, { nullable: true })
	thumbnail?: string = undefined

	@Field((type) => String, { nullable: true })
	icon?: string = undefined

	@Field((type) => Glass, { nullable: true })
	glass?: Glass = undefined

	@Field((type) => Int, { nullable: true })
	glassId?: number = undefined

	@Field((type) => [Technique])
	techniques: Technique[] = undefined

	@Field((type) => [Garnish])
	garnishes: Garnish[] = undefined

	@Field((type) => [Recipe])
	recipes: Recipe[] = undefined

	@Field((type) => [Ingredient])
	ingredients: Ingredient[] = undefined
}
