import { Author } from './author'
import { CompanyType } from '@prisma/client'
import { ObjectType, Field, ID, Int, registerEnumType } from '@nestjs/graphql'
import { GraphQLJSONObject } from 'graphql-type-json'

@ObjectType({
	description:
		'generated by [prisma-class-generator](https://github.com/kimjbstar/prisma-class-generator)',
})
export class Company {
	@Field((type) => ID)
	id: number = undefined

	@Field((type) => String)
	name: string = undefined

	@Field((type) => CompanyType)
	type: CompanyType = CompanyType.A

	@Field((type) => Date)
	createdAt: Date = undefined

	@Field((type) => Date)
	updatedAt: Date = undefined

	@Field((type) => Date, { nullable: true })
	deletedAt?: Date = undefined

	@Field((type) => [Author])
	authors: Author[] = undefined
}
registerEnumType(CompanyType, {
	name: 'CompanyType',
})
