import { Author } from './author'
import { ObjectType, Field, ID, Int, registerEnumType } from '@nestjs/graphql'
import { GraphQLJSONObject } from 'graphql-type-json'

@ObjectType({
	description:
		'generated by [prisma-class-generator](https://github.com/kimjbstar/prisma-class-generator)',
})
export class Post {
	@Field((type) => ID)
	id: number = undefined

	@Field((type) => String)
	name: string = undefined

	@Field((type) => Author)
	author: Author = undefined

	@Field((type) => Date)
	createdAt: Date = undefined

	@Field((type) => Date)
	updatedAt: Date = undefined

	@Field((type) => Date, { nullable: true })
	deletedAt?: Date = undefined

	@Field((type) => Int)
	authorId: number = undefined
}
