import { Cocktail } from './cocktail'
import { ObjectType, Field, ID, Int, registerEnumType } from '@nestjs/graphql'
import { GraphQLJSONObject } from 'graphql-type-json'

@ObjectType({
	description:
		'generated by [prisma-class-generator](https://github.com/kimjbstar/prisma-class-generator)',
})
export class Recipe {
	@Field((type) => ID)
	id: number = undefined

	@Field((type) => Cocktail)
	cocktail: Cocktail = undefined

	@Field((type) => Int)
	cocktailId: number = undefined

	@Field((type) => String)
	content: string = undefined
}
