import { UserRole } from '@prisma/client'
import { ObjectType, Field, ID, Int, registerEnumType } from '@nestjs/graphql'
import { GraphQLJSONObject } from 'graphql-type-json'

@ObjectType({
	description:
		'generated by [prisma-class-generator](https://github.com/kimjbstar/prisma-class-generator)',
})
export class User {
	@Field((type) => ID)
	id: number = undefined

	@Field((type) => String)
	email: string = undefined

	@Field((type) => String)
	name: string = undefined

	@Field((type) => String)
	password: string = undefined

	@Field((type) => String)
	salt: string = undefined

	@Field((type) => UserRole)
	role: UserRole = undefined

	@Field((type) => String, { nullable: true })
	addressRoad?: string = undefined

	@Field((type) => String, { nullable: true })
	addressDetail?: string = undefined

	@Field((type) => Int, { nullable: true })
	age?: number = undefined

	@Field((type) => Date, { nullable: true })
	lastLoginedAt?: Date = undefined

	@Field((type) => GraphQLJSONObject, { nullable: true })
	extra?: object = undefined

	@Field((type) => Date)
	createdAt: Date = undefined

	@Field((type) => Date)
	updatedAt: Date = undefined

	@Field((type) => Date, { nullable: true })
	deletedAt?: Date = undefined
}
registerEnumType(UserRole, {
	name: 'UserRole',
})
